<?xml version="1.0"?>
<!-- ############################### -->
<!-- URDF DESCRIPTION OF THE DOUBLE PENDULUM CRANE -->
<!-- October 2024                  -->
<!-- #########################################   -->

<robot name="crane" xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- Body dimensions -->
<xacro:property name="rope_length" value="4"/>
<xacro:property name="num_segments" value="10"/>
<xacro:property name="segment_length" value="${rope_length / num_segments}"/>
<xacro:property name="segment_mass" value="0.005"/>
<xacro:property name="segment_radius" value="0.1"/>
<xacro:property name="joint_radius" value="0.1"/>
<xacro:property name="cylinder_radius" value="0.1"/>
<xacro:property name="cylinder_length" value="8"/>



<material name="blue">
  <color rgba="0 0 0.8 1"/>
</material>
<material name="black">
  <color rgba="0 0 0 1"/>
</material>
<material name="white">
  <color rgba="1 1 1 1"/>
</material>
<material name="red">
  <color rgba="0.8 0 0 1"/>
</material>
<material name="red">
  <color rgba="0.8 0 0 1"/>
</material>
<material name="yellow">
  <color rgba="0.8 0.8 0 1"/>
</material>
<material name="blue">
  <color rgba="0 0 0.8 1"/>
</material>

<link name="world"/>

<link name ="base">
    <visual>
        <geometry>
        <mesh filename="package://crane/model/base_structure.stl" scale="1 1 1"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <material name="red"/>
  </visual>
   <collision>
    <geometry>
      <mesh filename="package://crane/model/base_structure.stl" scale="1 1 1" />
    </geometry>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </collision>
  <inertial>
    <mass value="500"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <inertia ixx="0.11379" ixy="-0.102" ixz="0.26544" iyy="15.372" iyz="0" izz="23.868"/>
  </inertial>
</link>
<gazebo reference="base">
  <material>Gazebo/Black</material>
</gazebo>

<joint name="base_joint" type="fixed">
    <parent link="world"/>
    <child link="base"/>
    <origin xyz="0 0 2" rpy="0 0 0"/>
</joint>

<link name="bridge">
  <visual>
    <geometry>
     <mesh filename="package://crane/model/bridge2stl.stl" scale="1 1 1"/>
    </geometry>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <material name="red"/>
  </visual>
  <collision>
    <geometry>
      <mesh filename="package://crane/model/bridge2stl.stl" scale="1 1 1" />
    </geometry>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <surface>
                <friction>
                    <ode>
                        <mu>0.5</mu>  
                    </ode>
                </friction>
            </surface>
  </collision>
  <inertial>
    <mass value="15"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.11379" ixy="-0.102" ixz="0.26544" iyy="15.372" iyz="0" izz="23.868"/>

        <!-- <inertia ixx="76.01" ixy="-4.20" ixz="0" iyy="84" iyz="-3.8" izz="83.25"/> -->

    <!-- <inertia ixx="109878.51" ixy="194167.83" ixz="542089.11" iyy="6582762.85" iyz="4869760.57" izz="26964922.34"/> -->
  </inertial>
</link>
<gazebo reference="bridge">
  <material>Gazebo/Yellow</material>
</gazebo>

<link name="cart">
  <visual>
    <geometry>
     <mesh filename="package://crane/model/cart2.stl" scale="1.1 1 1.1"/>
    </geometry>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <material name="red"/>
  </visual>
  <collision>
    <geometry>
      <mesh filename="package://crane/model/cart2.stl" scale="1.1 1 1.1" />
    </geometry>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <surface>
                <friction>
                    <ode>
                        <mu>0.1</mu>  
                    </ode>
                </friction>
            </surface>
  </collision>
  <inertial>
    <mass value="7"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
           <inertia ixx="76.01" ixy="-4.20" ixz="0" iyy="84" iyz="-3.8" izz="83.25"/> 

      <!-- <inertia ixx="38216.2" ixy="-427.38" ixz="-57148.34" iyy="-760.38" iyz="6738.98" izz="16903112.3"/> -->
  </inertial>
</link>
<gazebo reference="cart">
  <material>Gazebo/Orange</material>
</gazebo>

<xacro:macro name="prismatic_joint" params="name parent child x y z axis_x axis_y axis_z upper lower velocity damping">
  <joint name="${name}" type="prismatic">
    <parent link="${parent}"/>
    <child link="${child}"/>
    <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>

    <axis xyz="${axis_x} ${axis_y} ${axis_z}" rpy="0 0 0"/>
    <limit lower="${lower}" upper="${upper}" effort="1000" velocity="${velocity}"/>
    <dynamics damping="${damping}"/>
  </joint>
</xacro:macro>

<xacro:prismatic_joint name="bridge_joint" parent="base" child="bridge" x="0" y="0" z="0" axis_x="1" axis_y="0" axis_z="0" upper ="10" lower="-10" velocity = "5" damping="0"/>
<xacro:prismatic_joint name="cart_joint" parent="bridge" child="cart" x="0" y="0" z="-2" axis_x="0" axis_y="1" axis_z="0" upper ="17" lower="-17" velocity = "1" damping="0"/>

<xacro:macro name="bearing" params="name">
<link name="${name}">
      <visual>
        <geometry>
          <cylinder length="0.1" radius="0.05"/>
        </geometry>
        <material name="blue"/>

      </visual>
      <collision>
        <geometry>
          <cylinder length="0.1" radius="0.05"/>
        </geometry>
        <surface>
                <friction>
                    <ode>
                        <mu>0.1</mu>  
                    </ode>
                </friction>
            </surface>
      </collision>
      <inertial>
        <mass value="0.001"/>
        <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6"/>
      </inertial>
    </link>
   </xacro:macro>
   <xacro:bearing name="bearing" /> 
   <xacro:bearing name="bearing2" /> 
    <gazebo reference="bearing">
      <material>Gazebo/Black</material>
    </gazebo>

<xacro:macro name="pseudo" params="name">
 <link name="${name}">
   <visual>
        <geometry>
          <sphere radius="0.00005" />
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <material name="blue">
          <color rgba="0 0 1 1" />
        </material>
      </visual>
      <collision>
        <geometry>
          <sphere radius="0.00005" />
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <surface>
                <friction>
                    <ode>
                        <mu>0.1</mu>  
                    </ode>
                </friction>
            </surface>
      </collision>
      <inertial>
        <mass value="0.0001" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1" />
      </inertial>
  </link>
  </xacro:macro>

  <xacro:pseudo name="pseudo" />
<xacro:pseudo name="pseudo2" />

<xacro:macro name="fixed_joint" params="name parent child origin_xyz origin_rpy">
  <joint name="${name}" type="fixed">
    <parent link="${parent}"/>
    <child link="${child}"/>
    <origin xyz="${origin_xyz}" rpy="${origin_rpy}"/>
    <dynamics damping="0.0"/>
  </joint>
</xacro:macro>

  <joint name="cart_bearing" type="revolute">
    <parent link="cart"/>
    <child link="bearing"/>
    <origin xyz="0 0 22.5" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="-1.57" upper="1.57" effort="1000" velocity="1"/>
    <dynamics damping="0.5"/>

  </joint>
    <joint name="pseudo_joint_1" type="revolute">
    <parent link="bearing"/>
    <child link="pseudo"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1.57" upper="1.57" effort="1000" velocity="1"/>
    <dynamics damping="0.5"/>
  </joint>
  

  <joint name="load_rope" type="revolute">
    <parent link="segment_2_1_link"/>
    <child link="load"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 0"/>
    <limit lower="0" upper="0" effort="10000" velocity="0"/>
    <dynamics damping="0.5"/>
  </joint>

    <joint name="bearing2_joint" type="fixed">
    <parent link="load"/>
    <child link="bearing2"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1.57" upper="1.57" effort="1000" velocity="1"/>
    <dynamics damping="0.5"/>
  </joint>

  <joint name="pseudo2_joint" type="fixed">
    <parent link="bearing2"/>
    <child link="pseudo2"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="-1.57" upper="1.57" effort="10000" velocity="0"/>
    <dynamics damping="0.5"/>
  </joint>

    <joint name="rope_2_joint" type="fixed">
    <parent link="pseudo2"/>
    <child link="rope2"/>
    <origin xyz="0 0 -0.25" rpy="0 0 0"/>
    <axis xyz="0 0 0"/>
    <limit lower="0" upper="0" effort="10000" velocity="0"/>
    <dynamics damping="0.5"/>
  </joint>

  <joint name="load2_joint" type="revolute">
    <parent link="rope2"/>
    <child link="load2"/>
    <origin xyz="0 0 -4" rpy="0 0 0"/>
    <axis xyz="0 0 0"/>
    <limit lower="0" upper="0" effort="10000" velocity="0"/>
    <dynamics damping="0.5"/>
  </joint>

<xacro:macro name="rope_segment" params="prefix parent">
  <link name="${prefix}_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${segment_mass}"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${segment_length}" radius="${segment_radius}"/>
      </geometry>
      <material name="tether_material">
        <color rgba="1 1 0.1 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${segment_length}" radius="${segment_radius}"/>
      </geometry>
    </collision>
  </link>

  <joint name="${prefix}_joint" type="fixed">
    <parent link="${parent}"/>
    <child link="${prefix}_link"/>
    <origin xyz="0 0 -${segment_length}" rpy="0 0 0"/>
    <axis xyz="0 0 0"/>
    <limit lower="-1.57" upper="1.57" effort="1000" velocity="1"/>

  </joint>
   
</xacro:macro>

 <xacro:macro name="rope_recursive" params="num_segments parent_link">
  <xacro:if value="${num_segments > 0}">
    <xacro:property name="current_prefix" value="segment_2_${num_segments}" />
    <xacro:rope_segment prefix="${current_prefix}" parent="${parent_link}" />
    <xacro:rope_recursive num_segments="${num_segments - 1}" parent_link="${current_prefix}_link" />
  </xacro:if>
</xacro:macro>

<xacro:macro name="rope_2" params="num_segments">
  <xacro:property name="initial_parent" value="pseudo" />
  <xacro:rope_recursive num_segments="${num_segments}" parent_link="pseudo" />
</xacro:macro>

  <xacro:rope_2 num_segments="${num_segments}" />

<xacro:macro name="cylinder" params="name cylinder_length cylinder_radius mass">
    <link name="${name}">
      <visual>
      <origin xyz="0 0 ${-cylinder_length/2}" rpy="0 0 0" />
        <geometry>
          <cylinder length="${cylinder_length}" radius="${cylinder_radius}"/>
        </geometry>
      </visual>
      <collision>
      <origin xyz="0 0 ${-cylinder_length/2}" rpy="0 0 0" />
        <geometry>
          <cylinder length="${cylinder_length}" radius="${cylinder_radius}"/>
        </geometry>
      </collision>

      <inertial>
        <mass value="0.08" />
        <origin xyz="0 0 ${-cylinder_length/2}" rpy="0 0 0" />
        <inertia ixx="${0.25*mass*cylinder_radius*cylinder_radius + 0.083333333*mass*cylinder_length*cylinder_length}" 
                 ixy="0" ixz="0" 
                 iyy="${0.25*mass*cylinder_radius*cylinder_radius + 0.083333333*mass*cylinder_length*cylinder_length}"
                 iyz="0"
                 izz="${0.5*mass*cylinder_radius*cylinder_radius}" />
      </inertial>
    </link>
</xacro:macro>

  <!-- Call the macro to create a cylinder -->
<xacro:cylinder name="rope2" cylinder_length="4" cylinder_radius = "0.1" mass= "0.08" />


<xacro:macro name="load" params="name mass">
<link name="${name}">
      <visual>
        <geometry>
          <sphere radius="0.8" />
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <material name="blue">
          <color rgba="0 0 1 1" />
        </material>
      </visual>
      <collision>
        <geometry>
          <sphere radius="0.8" />
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0" />
      </collision>
      <inertial>
        <mass value="${mass}" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1" />
      </inertial>
    </link>
  </xacro:macro>
  <xacro:load name="load" mass="3" />
  <xacro:load name="load2"  mass="1"/>
    <gazebo reference="load">
      <material>Gazebo/Yellow</material>
    </gazebo>
<gazebo reference="load2">
      <material>Gazebo/Yellow</material>
    </gazebo>


  <!-- Transmissions -->

  <!-- <transmission name="bridge_transmission">
	<type>transmission_interface/SimpleTransmission</type>
	<joint name="bridge_joint">
	  <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
	</joint>
	<actuator name="world_bridge_motor">
	  <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
	  <mechanicalReduction>1</mechanicalReduction>
	</actuator>
  </transmission>

  <transmission name="cart_transmission">
	<type>transmission_interface/SimpleTransmission</type>
	<joint name="cart_joint">
	  <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
	</joint>
	<actuator name="cart_motor">
	  <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
	  <mechanicalReduction>1</mechanicalReduction>
	</actuator>
  </transmission>

    <transmission name="rope_transmission">
	<type>transmission_interface/SimpleTransmission</type>

	<joint name="cart_bearing">
	  <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
	</joint>
	<actuator name="load_motor">
	  <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
	  <mechanicalReduction>1</mechanicalReduction>
	</actuator>
  </transmission>

  <transmission name="pseudo_transmission">
	<type>transmission_interface/SimpleTransmission</type>

	<joint name="pseudo_joint_1">
	  <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
	</joint>
	<actuator name="pseudo_motor">
	  <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
	  <mechanicalReduction>1</mechanicalReduction>
	</actuator>
  </transmission>
  <gazebo> -->
  <!-- <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
    <robotNamespace>/</robotNamespace>
  </plugin> -->
<!-- </gazebo>  -->

</robot>

